// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN72sLfqEXfYjou8S4Vo3V7n7FFH5Mctw',
    appId: '1:481080430486:web:0b491a2b1629ce2e6c17b7',
    messagingSenderId: '481080430486',
    projectId: 'cartel-af494',
    authDomain: 'cartel-af494.firebaseapp.com',
    storageBucket: 'cartel-af494.firebasestorage.app',
    measurementId: 'G-HEW0T8H4CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn_mJRO7CjBZ4d_3ObJKsEVv8RgSlcSsE',
    appId: '1:481080430486:android:cbc244e9ca9331816c17b7',
    messagingSenderId: '481080430486',
    projectId: 'cartel-af494',
    storageBucket: 'cartel-af494.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMlKrmqkfkGQKCpzIU3_rNg5HRCQrIByE',
    appId: '1:481080430486:ios:868b43db12167f976c17b7',
    messagingSenderId: '481080430486',
    projectId: 'cartel-af494',
    storageBucket: 'cartel-af494.firebasestorage.app',
    iosBundleId: 'com.cartel.conciergerie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMlKrmqkfkGQKCpzIU3_rNg5HRCQrIByE',
    appId: '1:481080430486:ios:bde3505055b241fb6c17b7',
    messagingSenderId: '481080430486',
    projectId: 'cartel-af494',
    storageBucket: 'cartel-af494.firebasestorage.app',
    iosBundleId: 'com.cartel.cartelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN72sLfqEXfYjou8S4Vo3V7n7FFH5Mctw',
    appId: '1:481080430486:web:4bbe52dd9e7824936c17b7',
    messagingSenderId: '481080430486',
    projectId: 'cartel-af494',
    authDomain: 'cartel-af494.firebaseapp.com',
    storageBucket: 'cartel-af494.firebasestorage.app',
    measurementId: 'G-WM6TBNFVX9',
  );
}
